# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bq_tabledata_to_list <- function(x) {
    .Call(`_bigrquery_bq_tabledata_to_list`, x)
}

